version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing
    finally:
      - Install phase executed
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - ls -la
  post_build:
    commands: