version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Entered the installing phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Installing dependencies
    finally: 
      - echo This always runs even if the pre build phase commands fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm install
      # - ls -la
      # - printf "HOST=$DB_ADDRESS\nUSERNAME=dbusername\nPASSWORD=itsyourday\nDATABASE=$DB_NAME" > .env 
      # - zip express-miniapp.zip src src/* .env .eslintrc.js .gitignore buildspec.yml package-lock.json package.json .ebextensions .ebextensions/* node_modules node_modules/* README.md Procfile
      # - aws s3api create-bucket --bucket emercado-tier-1-code-37yyuj5midn7s --region us-east-1 || true
      # - aws s3 mv express-miniapp.zip s3://emercado-tier-1-code-37yyuj5midn7s --region us-east-1
    finally: 
      - echo This always runs even if the build phase commands fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*