version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
    finally: 
      - echo This always runs even if the pre build phase commands fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - ls -la
      - zip express-miniapp.zip .src .env .eslintrc.js .gitignore .buildspec.yml package-lock.json package.json node_modules README.md
      - aws s3 mb tier-1-DevOps-Challenge
    finally: 
      - echo This always runs even if the build phase commands fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'