version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing
      - npm install
    finally:
      - Install phase executed
  pre_build:
    commands:
  build:
    commands:
      - ls -la
  post_build:
    commands: