AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tier-1: Beginner Challenge - Elastic Beanstalk - CICD Stack

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket

  CodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
                - codedeploy.amazonaws.com
                - s3.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  #Code Build
  AppCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      # Name: tier-1-challenge-build
      # Description: Apper PH Technical Challenge Tier 1
      ServiceRole: !GetAtt CodePipelineServiceRole.Arn
      Cache:
        Type: S3
        Location: !Join [ "/", [ !Ref ArtifactBucket, "project_cache" ] ]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        # EnvironmentVariables:
        # - Name: varName
        #   Type: varType
        #   Value: varValue
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10
      # Tags:
      #   - Key: Key1
      #     Value: Value1
      #   - Key: Key2
      #     Value: Value2

  #Code Pipeline
  AppPipeline: 
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages: 
        - 
          Name: Source 
          Actions: 
            - 
              Name: SourceAction
              ActionTypeId: 
                Category: Source 
                Owner: AWS 
                Version: '1' 
                Provider: CodeStarSourceConnection          
              OutputArtifacts: 
                - 
                  Name: SourceArtifact 
              Configuration: 
                ConnectionArn: !GetAtt CodeStarConnection.ConnectionArn
                FullRepositoryId: edwardmercado/apper-devops-technical-challenge-tier-1
                BranchName: main
                OutputArtifactFormat: CODE_ZIP
              RunOrder: 1 
        - 
          Name: Beta 
          Actions: 
            - 
              Name: BetaAction 
              InputArtifacts: 
                -
                  Name: SourceArtifact
              ActionTypeId: 
                Category: Build 
                Owner: AWS
                Version: 1 
                Provider: CodeBuild
              Configuration: 
                ProjectName: tier-1-challenge-build
              RunOrder: 1 
        # - 
        #   Name: Release 
        #   Actions: 
        #     - 
        #       Name: ReleaseAction
        #       InputArtifacts: 
        #         - 
        #           Name: SourceOutput 
        #       ActionTypeId: 
        #         Category: Deploy 
        #         Owner: AWS 
        #         Version: 1
        #         Provider: CodeDeploy 
        #       Configuration: 
        #         ApplicationName: 
        #           Ref: ApplicationName
        #         DeploymentGroupName: 
        #           Ref: DeploymentGroupName 
        #       RunOrder: 1 
      # ArtifactStore: 
      #   Type: S3 
      #   Location: !GetAtt ArtifactBucket.Arn

  CodeStarConnection:
    Type: 'AWS::CodeStarConnections::Connection'
    Properties:
      ConnectionName: GitHubToPipelineConnection-tier1
      ProviderType: GitHub


#Outputs:
