AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tier-1: Beginner Challenge - Elastic Beanstalk - CDN Stack

Resources:
  ##CloudFront
  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: myACMCert
    Properties:
      DistributionConfig:
        Aliases: 
          - emercado-tier1.apperdevops.com
        Origins:
          - DomainName:
              Fn::ImportValue:
                EBAppURLName
            Id: emercado-tier1.apperdevops.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_200
        Enabled: true
        ViewerCertificate: 
          AcmCertificateArn: !Ref myACMCert
          SslSupportMethod: sni-only
        DefaultCacheBehavior: 
          TargetOriginId: emercado-tier1.apperdevops.com
          SmoothStreaming: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 86400
          MaxTTL: 259200
          MinTTL: 43200
  
  #ACM CERT
  myACMCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "*.apperdevops.com"
      DomainValidationOptions:
        - DomainName: "*.apperdevops.com"
          ValidationDomain: "*.apperdevops.com"
      ValidationMethod: DNS

  #R53 Record
  route53RS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z08257801AI6TNNWIWVBW #registered
      Name: emercado-tier1.apperdevops.com
      Type: A
      AliasTarget: 
        DNSName: !GetAtt cloudfrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2