AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tier-1: Beginner Challenge - Elastic Beanstalk - CDN Stack

Resources:
  ##CloudFront
  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origin:
          - DomainName:
              Fn::ImportValue:
                EBAppURLName
            Id: emercado-tier1.apperdevops.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior: 
          TargetOriginId: emercado-tier1.apperdevops.com
          SmoothStreaming: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https